// FBR Sandbox Scenarios — official list from FBR Digital Invoice portal

export interface FBRScenarioTestBuyer {
  ntnCnic: string;
  businessName: string;
  province: string;
  address: string;
  registrationType: 'Registered' | 'Unregistered';
}

export interface FBRScenarioTestItem {
  hsCode: string;
  productDescription: string;
  rate: string;
  uom: string;
  quantity: number;
  valueSalesExcludingST: number;
  fixedNotifiedValueOrRetailPrice: number;
  salesTaxApplicable: number;
  salesTaxWithheldAtSource: number;
  extraTax: number;
  furtherTax: number;
  sroScheduleNo: string;
  fedPayable: number;
  discount: number;
  saleType: string;
  sroItemSerialNo: string;
  totalValues: number;
}

export interface FBRScenarioTestData {
  buyer: FBRScenarioTestBuyer;
  item: FBRScenarioTestItem;
  invoiceRefNo: string;
}

export interface FBRScenario {
  id: string;
  description: string;
  saleType: string;
  taxVariant: string;
  requiredFields: string[];
  notes?: string;
  testData: FBRScenarioTestData;
}

export const FBR_SCENARIOS: FBRScenario[] = [
  {
    id: 'SN001',
    description: 'Standard Rate - Registered Buyer',
    saleType: 'Goods at standard rate (default)',
    taxVariant: '18%',
    requiredFields: ['buyerNTNCNIC', 'hsCode', 'rate'],
    notes: 'Most common scenario. Buyer is registered for sales tax.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '0101.2100',
        productDescription: 'Test Item - Standard Rate - Registered Buyer',
        rate: '18%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Goods at standard rate (default)',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN002',
    description: 'Standard Rate - Unregistered Buyer',
    saleType: 'Goods at standard rate (default)',
    taxVariant: '18% + 2% further tax',
    requiredFields: ['hsCode', 'rate', 'furtherTax'],
    notes: 'Buyer is unregistered. 2% further tax applies on top of 18%.',
    testData: {
      buyer: {
        ntnCnic: '1000000000000',
        businessName: 'Unregistered Buyer',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Unregistered',
      },
      item: {
        hsCode: '0101.2100',
        productDescription: 'Test Item - Standard Rate - Unregistered Buyer',
        rate: '18%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 20,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Goods at standard rate (default)',
        sroItemSerialNo: '',
        totalValues: 1200,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN003',
    description: 'Steel (Melted & Re-Rolled)',
    saleType: 'Steel (Melted and Re-Rolled)',
    taxVariant: '17%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of steel billets, ingots and long bars at 17% ST.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '7214.2000',
        productDescription: 'Test Item - Steel Melted and Re-Rolled',
        rate: '17%',
        uom: 'Metric Ton',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 170,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Steel (Melted and Re-Rolled)',
        sroItemSerialNo: '',
        totalValues: 1170,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN004',
    description: 'Steel Scrap by Ship Breakers',
    saleType: 'Steel scrap sold by ship breakers',
    taxVariant: '17%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of steel scrap by ship breaking yards at 17% ST.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '7204.1000',
        productDescription: 'Test Item - Steel Scrap Ship Breakers',
        rate: '17%',
        uom: 'Metric Ton',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 170,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Steel scrap sold by ship breakers',
        sroItemSerialNo: '',
        totalValues: 1170,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN005',
    description: 'Reduced Rate Goods',
    saleType: 'Goods at Reduced Rate',
    taxVariant: '1%',
    requiredFields: ['hsCode', 'rate', 'sroScheduleNo'],
    notes: 'Goods attracting reduced ST rate under SRO exemption.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '0102.2930',
        productDescription: 'Test Item - Reduced Rate Goods',
        rate: '1%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 10,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        fedPayable: 0,
        discount: 0,
        saleType: 'Goods at Reduced Rate',
        sroItemSerialNo: '82',
        totalValues: 1010,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN006',
    description: 'Exempt Goods',
    saleType: 'Exempt goods',
    taxVariant: '0%',
    requiredFields: ['hsCode', 'saleType'],
    notes: 'Goods completely exempt from sales tax under Sixth Schedule.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '0102.2930',
        productDescription: 'Test Item - Exempt Goods',
        rate: '0%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 0,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '6th Schd Table I',
        fedPayable: 0,
        discount: 0,
        saleType: 'Exempt goods',
        sroItemSerialNo: '100',
        totalValues: 1000,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN007',
    description: 'Zero-Rated Sale',
    saleType: 'Goods at zero-rate',
    taxVariant: '0%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Zero-rated goods — distinct from exempt, used for exports (Fifth Schedule).',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '0101.2100',
        productDescription: 'Test Item - Zero Rated Sale',
        rate: '0%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 0,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '327(I)/2008',
        fedPayable: 0,
        discount: 0,
        saleType: 'Goods at zero-rate',
        sroItemSerialNo: '1',
        totalValues: 1000,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN008',
    description: '3rd Schedule Goods',
    saleType: '3rd Schedule Goods',
    taxVariant: '18% on retail price',
    requiredFields: ['hsCode', 'rate', 'fixedNotifiedValueOrRetailPrice'],
    notes: 'Goods taxed on retail/notified price under Third Schedule.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '3304.9900',
        productDescription: 'Test Item - 3rd Schedule Goods',
        rate: '18%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 847,
        fixedNotifiedValueOrRetailPrice: 1000,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: '3rd Schedule Goods',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN009',
    description: 'Cotton Ginners Purchase',
    saleType: 'Cotton ginners',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Purchase invoice from registered cotton ginners.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '5201.0000',
        productDescription: 'Test Item - Raw Cotton',
        rate: '18%',
        uom: 'Metric Ton',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Cotton ginners',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN010',
    description: 'Telecom Services',
    saleType: 'Mobile/Telecom Services',
    taxVariant: '19.5%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of telecom services by mobile operators at 19.5% GST.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '8517.1200',
        productDescription: 'Test Item - Telecom Services',
        rate: '19.5%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 195,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Mobile/Telecom Services',
        sroItemSerialNo: '',
        totalValues: 1195,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN011',
    description: 'Steel Toll Manufacturing',
    saleType: 'Steel through Toll Manufacturing',
    taxVariant: '17%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of steel through toll manufacturing process.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '7214.2000',
        productDescription: 'Test Item - Steel Toll Manufacturing',
        rate: '17%',
        uom: 'Metric Ton',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 170,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Steel through Toll Manufacturing',
        sroItemSerialNo: '',
        totalValues: 1170,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN012',
    description: 'Petroleum Products',
    saleType: 'Petroleum products',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of petroleum products (motor spirit, HSD, etc.).',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '2710.1200',
        productDescription: 'Test Item - Petroleum Products',
        rate: '18%',
        uom: 'Litre',
        quantity: 1000,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Petroleum products',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN013',
    description: 'Electricity to Retailers',
    saleType: 'Electricity',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of electricity to retailers/end consumers by DISCOs.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '2716.0000',
        productDescription: 'Test Item - Electricity',
        rate: '18%',
        uom: 'KWH',
        quantity: 1000,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Electricity',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN014',
    description: 'Gas to CNG Stations',
    saleType: 'Gas',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of natural gas to CNG stations by gas utility companies.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '2711.2100',
        productDescription: 'Test Item - Gas to CNG Stations',
        rate: '18%',
        uom: 'MMBTU',
        quantity: 100,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Gas',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN015',
    description: 'Mobile Phones',
    saleType: 'Mobile phones',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of mobile phones with specific ST treatment.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '8517.1200',
        productDescription: 'Test Item - Mobile Phones',
        rate: '18%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Mobile phones',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN016',
    description: 'Processing/Conversion',
    saleType: 'Processing/Conversion of Goods',
    taxVariant: '5%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Invoice raised for processing or conversion services on goods.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '0101.2100',
        productDescription: 'Test Item - Processing Conversion',
        rate: '5%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 50,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Processing/Conversion of Goods',
        sroItemSerialNo: '',
        totalValues: 1050,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN017',
    description: 'Goods (FED in ST Mode)',
    saleType: 'Goods (FED in ST Mode)',
    taxVariant: '8% + FED',
    requiredFields: ['hsCode', 'rate', 'fedPayable'],
    notes: 'Federal Excise Duty charged in Sales Tax mode alongside ST.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '2402.2000',
        productDescription: 'Test Item - Goods FED in ST Mode',
        rate: '8%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 80,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 65,
        discount: 0,
        saleType: 'Goods (FED in ST Mode)',
        sroItemSerialNo: '',
        totalValues: 1145,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN018',
    description: 'Services (FED in ST Mode)',
    saleType: 'Services (FED in ST Mode)',
    taxVariant: '13% + FED',
    requiredFields: ['hsCode', 'rate', 'fedPayable', 'saleType'],
    notes: 'Sale of services where FED is charged in ST mode.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '9805.1000',
        productDescription: 'Test Item - Services FED in ST Mode',
        rate: '13%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 130,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 50,
        discount: 0,
        saleType: 'Services (FED in ST Mode)',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN019',
    description: 'Services (ICT Ordinance)',
    saleType: 'Services (ICT Ordinance)',
    taxVariant: '15%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of IT/telecom services under ICT Ordinance 2001.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '8523.8000',
        productDescription: 'Test Item - Services ICT Ordinance',
        rate: '15%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 150,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Services (ICT Ordinance)',
        sroItemSerialNo: '',
        totalValues: 1150,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN020',
    description: 'Electric Vehicles',
    saleType: 'Electric Vehicles',
    taxVariant: '1%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of electric vehicles at reduced 1% ST under EV policy.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '8703.8000',
        productDescription: 'Test Item - Electric Vehicle',
        rate: '1%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 5000000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 50000,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: 'FIFTH SCHEDULE',
        fedPayable: 0,
        discount: 0,
        saleType: 'Electric Vehicles',
        sroItemSerialNo: '',
        totalValues: 5050000,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN021',
    description: 'Cement/Concrete Block',
    saleType: 'Cement/Concrete Block',
    taxVariant: 'Rs.3 per kg',
    requiredFields: ['hsCode', 'rate', 'saleType', 'fixedNotifiedValueOrRetailPrice'],
    notes: 'Sale of cement at fixed ST rate per kg under Third Schedule.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '2523.2900',
        productDescription: 'Test Item - Cement',
        rate: '18%',
        uom: 'Metric Ton',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 1200,
        salesTaxApplicable: 216,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Cement/Concrete Block',
        sroItemSerialNo: '',
        totalValues: 1216,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN022',
    description: 'Potassium Chlorate',
    saleType: 'Potassium Chlorate',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of potassium chlorate — controlled chemical with specific ST rules.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '2829.1100',
        productDescription: 'Test Item - Potassium Chlorate',
        rate: '18%',
        uom: 'Metric Ton',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Potassium Chlorate',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN023',
    description: 'CNG Sales',
    saleType: 'CNG',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of compressed natural gas by CNG stations.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '2711.2100',
        productDescription: 'Test Item - CNG',
        rate: '18%',
        uom: 'KG',
        quantity: 100,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'CNG',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN024',
    description: 'SRO 297 Goods',
    saleType: 'Goods as per SRO.297(I)/2023',
    taxVariant: '25%',
    requiredFields: ['hsCode', 'rate', 'sroScheduleNo', 'sroItemSerialNo'],
    notes: 'Goods under SRO 297(I)/2023 — luxury/specific rate with SRO reference.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '0101.2100',
        productDescription: 'Test Item - SRO 297 Goods',
        rate: '25%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 250,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '297(I)/2023-Table-I',
        fedPayable: 0,
        discount: 0,
        saleType: 'Goods as per SRO.297(I)/2023',
        sroItemSerialNo: '12',
        totalValues: 1250,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN025',
    description: 'Drugs (Fixed ST Rate)',
    saleType: 'Drugs at fixed ST rate',
    taxVariant: 'Fixed rate (Eighth Schedule, Serial 81)',
    requiredFields: ['hsCode', 'rate', 'saleType', 'fixedNotifiedValueOrRetailPrice'],
    notes: 'Drugs sold at fixed ST rate per Serial 81 of the Eighth Schedule.',
    testData: {
      buyer: {
        ntnCnic: '2046004',
        businessName: 'FERTILIZER MANUFAC IRS NEW',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Registered',
      },
      item: {
        hsCode: '3004.9090',
        productDescription: 'Test Item - Drugs Fixed ST Rate',
        rate: '1%',
        uom: 'Numbers, pieces, units',
        quantity: 100,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 1100,
        salesTaxApplicable: 11,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        fedPayable: 0,
        discount: 0,
        saleType: 'Drugs at fixed ST rate',
        sroItemSerialNo: '81',
        totalValues: 1011,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN026',
    description: 'Retailer - Standard Rate',
    saleType: 'Goods at standard rate (default)',
    taxVariant: '18%',
    requiredFields: ['hsCode', 'rate', 'saleType'],
    notes: 'Sale of standard rate goods to end consumers by registered retailers.',
    testData: {
      buyer: {
        ntnCnic: '1000000000000',
        businessName: 'End Consumer',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Unregistered',
      },
      item: {
        hsCode: '0101.2100',
        productDescription: 'Test Item - Retailer Standard Rate',
        rate: '18%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: 'Goods at standard rate (default)',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN027',
    description: 'Retailer - 3rd Schedule',
    saleType: '3rd Schedule Goods',
    taxVariant: '18% on retail price',
    requiredFields: ['hsCode', 'rate', 'fixedNotifiedValueOrRetailPrice'],
    notes: 'Sale of 3rd Schedule goods to end consumers by retailers.',
    testData: {
      buyer: {
        ntnCnic: '1000000000000',
        businessName: 'End Consumer',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Unregistered',
      },
      item: {
        hsCode: '3304.9900',
        productDescription: 'Test Item - Retailer 3rd Schedule',
        rate: '18%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 847,
        fixedNotifiedValueOrRetailPrice: 1000,
        salesTaxApplicable: 180,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: '',
        fedPayable: 0,
        discount: 0,
        saleType: '3rd Schedule Goods',
        sroItemSerialNo: '',
        totalValues: 1180,
      },
      invoiceRefNo: '',
    },
  },
  {
    id: 'SN028',
    description: 'Retailer - Reduced Rate',
    saleType: 'Goods at Reduced Rate',
    taxVariant: '1%',
    requiredFields: ['hsCode', 'rate', 'sroScheduleNo'],
    notes: 'Sale of reduced rate goods to end consumers by retailers.',
    testData: {
      buyer: {
        ntnCnic: '1000000000000',
        businessName: 'End Consumer',
        province: 'Sindh',
        address: 'Karachi',
        registrationType: 'Unregistered',
      },
      item: {
        hsCode: '0102.2930',
        productDescription: 'Test Item - Retailer Reduced Rate',
        rate: '1%',
        uom: 'Numbers, pieces, units',
        quantity: 1,
        valueSalesExcludingST: 1000,
        fixedNotifiedValueOrRetailPrice: 0,
        salesTaxApplicable: 10,
        salesTaxWithheldAtSource: 0,
        extraTax: 0,
        furtherTax: 0,
        sroScheduleNo: 'EIGHTH SCHEDULE Table 1',
        fedPayable: 0,
        discount: 0,
        saleType: 'Goods at Reduced Rate',
        sroItemSerialNo: '82',
        totalValues: 1010,
      },
      invoiceRefNo: '',
    },
  },
];

/** Look up a scenario by ID */
export function getScenario(id: string): FBRScenario | undefined {
  return FBR_SCENARIOS.find((s) => s.id === id);
}
